FROM localhost/dcu-devcade-onboard:latest

# set passwords and set devcade acc to not expire
RUN chage -E -1 devcade;    \
    passwd --delete devcade 

# disable autologin
RUN systemctl disable getty@tty1

# different bash init file
COPY .bashrc /etc/bashrc

# copy over new exe's
COPY tmp/onboard/ /usr/bin/

### cleanup
# remove all log files, runtime only, and temporary files
RUN rm -rf /var;        \
    rm -rf /run;        \
    rm -rf /tmp;        \
    mkdir -p /var/home; \
    mkdir -p /run;      \
    mkdir -p /tmp;

# make it known as a bootc container
LABEL containers.bootc=1
LABEL bootc.rootfs=/sysroot

RUN bootc container lint