FROM quay.io/fedora/fedora-bootc:43

# user and file systemd configs
COPY ./dcu/config-files/files.conf /usr/lib/tmpfiles.d/custom_files.conf
COPY ./dcu/config-files/users.conf /usr/lib/sysusers.d/custom_users.conf

# disable sleep/hiberate features
RUN systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

### required software
RUN dnf install -y                                                  \
    openbox picom awk scrot xterm pamixer xdg-desktop-portal-gtk    \
    gcc-c++ git wget unzip dotnet-sdk-10.0                          \
    grep openssh-server openssl-devel fail2ban                      \
    glib2-devel flatpak-devel libnfc-devel                          \
    make cmake                                                      \
    autoconf automake libtool                                       \
    xrandr @base-x                                                  \
    plymouth-plugin-script

# install libfreefare-devel, as it is not in the package manager yet
RUN git clone https://github.com/nfc-tools/libfreefare.git &&   \
    cd libfreefare &&                                           \
    autoreconf -vis &&                                          \
    ./configure --prefix=/usr &&                                \
    make && make install &&                                     \
    cd .. && rm -r libfreefare

# required flatpak runtimes
RUN flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo &&   \
    flatpak install -y flathub org.freedesktop.Platform/x86_64/22.08

# root services config file
# ban people from ssh'ing after some number of attempts for some amount of time (see contents of file for specifics)
COPY ./dcu/config-files/sshd.local /etc/fail2ban/jail.d/sshd.local
# ssh server configuration file
COPY ./dcu/config-files/sshd_config /etc/ssh/sshd_config
RUN systemctl enable fail2ban; \
    systemctl enable sshd

# # copy boot splash over
# COPY ./boot-splash/devcade /usr/share/plymouth/themes/devcade
# # set theme
# RUN ls -l /usr/share/plymouth/themes &&     \
#     plymouth-set-default-theme -R devcade 

# install Rust
RUN mkdir -p /var/roothome && \
    curl https://sh.rustup.rs -sSf | bash -s -- -y; 
ENV PATH "/root/.cargo/bin:${PATH}"

# install godot 4.7-stable mono
RUN wget "https://github.com/godotengine/godot/releases/download/4.7-stable/Godot_v4.7-stable_mono_linux_x86_64.zip" &&         \
    unzip Godot_v4.7-stable_mono_linux_x86_64.zip &&                                                                            \
    mv Godot_v4.7-stable_mono_linux_x86_64/Godot_v4.7-stable_mono_linux.x86_64 /usr/bin/Godot_v4.7-stable_mono_linux.x86_64 &&  \
    mv Godot_v4.7-stable_mono_linux_x86_64/GodotSharp /usr/bin/GodotSharp;                                                      \
    rm Godot_v4.7-stable_mono_linux_x86_64.zip

### copy required files 
# NOTE: required symlinks for some config files are created in dcu/config-files/files.conf
# ostree settings
COPY ./dcu/config-files/prepare-root.conf /usr/lib/ostree/prepare-root.conf

# openbox config file
COPY ./dcu/config-files/rc.xml /etc/xdg/openbox/rc.xml 

# x11 init file
COPY ./dcu/config-files/.xinitrc /etc/X11/xinit/xinitrc  

# bash init file
COPY ./dcu/config-files/.bashrc /etc/bashrc

# autologin service
COPY ./dcu/config-files/tty1_service_override.conf /etc/systemd/system/getty@tty1.service.d/override.conf

# required custom executables
COPY ./dcu/config-files/export-all /usr/share/devcade/
COPY ./dcu/config-files/devcade_onboard /usr/bin/
COPY ./HACKING/tmp/godot /usr/bin/

RUN mkdir -p /usr/share/devcade/
COPY ./onboard/.env.template /usr/share/devcade/.env.template


# niceity software
RUN dnf install -y                          \
    vim fastfetch btop lspci usbutils gdb   \
    && dnf clean all

# set passwords and set devcade acc to not expire
RUN chage -E -1 devcade;    \
    passwd --delete devcade 

# disable autologin
RUN systemctl disable getty@tty1

# different bash init file
COPY /HACKING/.bashrc /etc/bashrc

### cleanup
# remove all log files, runtime only, and temporary files
RUN rm -rf /var;        \
    rm -rf /run;        \
    rm -rf /tmp;        \
    mkdir -p /var/home; \
    mkdir -p /run;      \
    mkdir -p /tmp;

# make it known as a bootc container
LABEL containers.bootc=1
LABEL bootc.rootfs=/sysroot

RUN bootc container lint