
animation_images = [];

screen_width = Window.GetWidth();
screen_height = Window.GetHeight();

# Get the original dimensions
image = Image("0150.png");
image_width = image.GetWidth();
image_height = image.GetHeight();

# Create sprite
animation_sprite = Sprite();
animation_sprite.SetImage(image);

# Center it
animation_sprite.SetX((screen_width - image_width) / 2);
animation_sprite.SetY((screen_height - image_height) / 2);
animation_sprite.SetZ(1);

Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

fun on_refresh() {
}

Plymouth.SetRefreshFunction(on_refresh);
