
services:
  devcade-onboard:
    build:
      args:
        USERNAME_VAR: ${USERNAME_VAR}
        PASSWORD_VAR: ${PASSWORD_VAR}
    ports:
      - "2200:22"
    volumes:
      - ssh_authed_keys:/var/home/${USERNAME_VAR}/.ssh/
      - ssh_host_keys:/etc/ssh/
  
volumes:
  ssh_authed_keys:
  ssh_host_keys: