#!/bin/bash

# first arg is --help or -h             or # of args != 3
if [[ $1 == --help ]] || [[ $1 == -h ]] || [[ $# -ne 3 ]]; then
    echo "Usage:" $0 "<godot_executable> <path_to_root_folder> <out_path>" 
    exit
fi

# backend
# cargo build the backend cause yeah
cd $2/onboard/backend
cargo build --release
cd $2
cp $2/onboard/backend/target/release/backend $3/devcade_backend

# godot frontend
$1 --path $2/onboard/godot-frontend --headless --export-debug "Linux" $3/devcade_frontend

exit