#!/bin/bash

# first arg is --help or -h             or # of args != 3
if [[ $1 == --help ]] || [[ $1 == -h ]] || [[ $# -ne 3 ]]; then
    echo "Usage:" $0 "<godot_executable> <path_to_root_folder> <out_path>" 
    exit
fi

# backend
# cargo build the backend cause yeah
cd $2/onboard/backend
cargo build --release
cd $2
cp $2/onboard/backend/target/release/backend $3/devcade_backend

# godot frontend
/usr/bin/dotnet build "$2/onboard/godot-frontend/godot-frontend.csproj" -c Release
echo "build solutions return code"
echo $?
$1 --verbose --quit --no-addons --path $2/onboard/godot-frontend --headless --export-release "Linux" $3/devcade_frontend
echo "compile return code"
echo $?

exit