#https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html# 
#Type   Path                                    Mode    User        Group       Age     Argument
d       /var/home/devcade                       -       devcade     devcade     -       -
d       /var/home/devcade/.local/share/xorg/    -       devcade     devcade     -       -