# see https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html
#Type   Path                                    Mode    User        Group       Age     Argument
d       /var/home/devcade/                      755     devcade     devcade     -       -
d       /var/home/devcade/.local/share/xorg/    755     devcade     devcade     -       -
d       /var/home/devcade/.local/               755     devcade     devcade     -       -
d       /var/home/devcade/.local/share/         755     devcade     devcade     -       -
d       /var/home/devcade/.local/share/godot/   755     devcade     devcade     -       -

# L+ forces a symlink to be created
#Type   Symlink to create                                                           Mode    User    Group   Age Target_path
L+      /var/home/devcade/.local/share/godot/export_templates/                      -       devcade devcade -   /usr/share/godot/export_templates/
L+      /var/home/devcade/.env                                                      -       devcade devcade -   /usr/share/devcade/.env
