# see: https://www.freedesktop.org/software/systemd/man/latest/sysusers.d.html
#Type Name       ID       GECOS              Home directory      Shell
u     devcade    -        "Devcade User"     /var/home/devcade   /bin/sh
u!    root       -        "Root User"        "-"                 /usr/sbin/nologin
