#!/bin/sh

DEVCADE_OUTPUT=HDMI-2

#xrandr --newmode "2560x1080_75.00" 294.00 2560 2744 3016 3472 1080 1083 1093 1130 -hsync +vsync --verbose
#
#xrandr --addmode $DEVCADE_OUTPUT 2560x1080_75.00 --verbose
#
#xrandr --output $DEVCADE_OUTPUT --mode 2560x1080_75.00 --rotate left  --verbose

source ~/.env
openbox & compton & pulseaudio &
~/publish/onboard

